% TODO: load training dataset

% TODO: reshape and adjust the dimensions to be in the order of [height,width,1,sample_index]
load('../data/nist36_train.mat');
data = reshape(train_data',[32,32,1,size(train_data,1)]);
% data = double(data < 0.4);
% labels = train_labels;


layers = define_autoencoder();

options = trainingOptions('sgdm',...
                          'InitialLearnRate',1e-3,...
                          'LearnRateSchedule','None',...
                          'LearnRateDropFactor',0.2,...
                          'LearnRateDropPeriod',5,...
                          'MaxEpochs',3,...
                          'MiniBatchSize',20,...
                          'Shuffle','every-epoch',...
                          'Plot','training-progress',...
                          'VerboseFrequency',20);

% TODO: run trainNetwork()
net = trainNetwork(data,data,layers,options);

                      